# Generated by Django 4.0.3 on 2022-03-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0002_alter_person_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_pub',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content_pub',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content_pub',
            name='videos_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='Trombinoscoop.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='img_profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
