# Generated by Django 4.0.3 on 2022-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0003_alter_content_pub_img_alter_content_pub_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='content_fk',
        ),
        migrations.AddField(
            model_name='publication',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='videos_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Content_pub',
        ),
    ]
