# Generated by Django 4.0.3 on 2022-04-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0004_remove_publication_content_fk_publication_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, to='Trombinoscoop.person'),
        ),
    ]
