# Generated by Django 4.0.3 on 2022-04-03 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0005_alter_person_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='comment',
        ),
        migrations.AlterField(
            model_name='publication',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Comment_pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('author_fk', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.person')),
                ('comment_cm', models.ManyToManyField(blank=True, to='Trombinoscoop.comment_pub')),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.publication')),
            ],
        ),
    ]
