# Generated by Django 4.0.3 on 2022-04-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0006_remove_publication_comment_alter_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='nb_like',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='nb_sharing',
            field=models.IntegerField(blank=True),
        ),
    ]
