# Generated by Django 4.0.3 on 2022-04-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0007_alter_publication_nb_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='nb_like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='nb_sharing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
