# Generated by Django 4.0.3 on 2022-04-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0009_alter_publication_author_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author_fk',
        ),
        migrations.AddField(
            model_name='person',
            name='author_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.person'),
        ),
    ]
