# Generated by Django 4.0.3 on 2022-04-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0010_remove_publication_author_fk_person_author_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='author_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.publication'),
        ),
    ]
