# Generated by Django 4.0.3 on 2022-04-05 19:20

import Trombinoscoop.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0011_alter_person_author_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='author_fk',
        ),
        migrations.AddField(
            model_name='publication',
            name='author_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Trombinoscoop.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='img_profile',
            field=models.FileField(blank=True, default=None, null=True, upload_to='profil_img/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='img',
            field=models.FileField(blank=True, upload_to=Trombinoscoop.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='publication',
            name='videos_path',
            field=models.FileField(blank=True, upload_to=Trombinoscoop.models.user_directory_path),
        ),
    ]
