# Generated by Django 4.0.3 on 2022-04-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trombinoscoop', '0012_remove_person_author_fk_publication_author_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='registration_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
